Testing: Testing.c SelectionSort.c SelectionSort.h Bubblesort.c Bubblesort.h MergeSort.c MergeSort.h InsertionSort.c InsertionSort.h
	gcc Testing.c SelectionSort.c Bubblesort.c MergeSort.c InsertionSort.c Timer.c -o Testing
